### ISSUE TITLE
Accept OMOP ES batches

### ISSUE THREAD

**Issue by stefpiatek** [SAFEHR-data/PIXL#231]
### Definition of Done / Acceptance Criteria

- [ ] PIXL CLI reads from multiple batches, within a single OMOP ES. Populating the queues as if it were a single batch
- [ ] PIXL CLI copies the public files from multiple batches into the extracts directory 
- [ ] Assuming #192 is completed, then should refactor this to copy the directory structure rather thsn globbing

### Testing

- [ ] Will need to have a test example with multiple batches
- [ ] If we have tests for copying parquet files via SFTP then this should also be tested, but if not this can be done when we implement the parquet uploading

### Documentation

Update CLI documentation

### Details and Comments

Expected structure for a single project which is split up over 3 batches (this would happen when there is a large amount of data and we want to ensure ease of transferring. 
```
└── omop_extract
    ├── extract_1
    │   ├── extract_summary.json
    │   ├── private
    │   └── public
    ├── extract_2
    │   ├── extract_summary.json
    │   ├── private
    │   └── public
    └── extract_3
        ├── extract_summary.json
        ├── private
        └── public
```
Where `omop_extract` is the directory that is passed into `pixl populate`. `extract_*` are expected to be literal dir names.

**Comment by jeremyestein** [comment]
I think it's worth checking our assumptions. The project_name + datetime combination that we are using to define an "extract" will be the same for each of the batches within this extract, right? And each batch is identified only by its directory name?

**Comment by stefpiatek** [comment]
> The project_name + datetime combination that we are using to define an "extract" will be the same for each of the batches within this extract, right? 

Yep!

> And each batch is identified only by its directory name?

I'm not quite sure what you mean here, will follow up in person (if I don't then prod me!) and comment here but I expect the answer is yes.

**Comment by stefpiatek** [comment]
OMOP ES will merge parquet batches so not needed in the end
