### ISSUE TITLE
Fix buggy system test in CI

### ISSUE THREAD

**Issue by stefpiatek** [SAFEHR-data/PIXL#465]
### Definition of Done / Acceptance Criteria

- [ ] Understand the bug and fix it (see details)
- [ ] Try running action a few times in CI to make sure that doesn't crop up

### Details and Comments

With the exact same version of the code the system tests sometimes have a failure. Haven't looked but I think it might be fixed by checking `('ANONYMIZED', 'include123')` is in the set, rather than the two sets are equal. Would need to check that makes sense for the requirements of the test

```
 FAILED system_test.py::TestFtpsUpload::test_ftps_dicom_upload - AssertionError: assert {('ANONYMIZED', 'include123')} == {('ANONYMIZED...'include123')}
  
  Extra items in the right set:
  ('ANONYMIZED', 'AP')
  
  Full diff:
    {
  -     (
  -         'ANONYMIZED',
  -         'AP',
  -     ),
        (
            'ANONYMIZED',
            'include123',
        ),
    }
```

[passing action](https://github.com/UCLH-Foundry/PIXL/actions/runs/10178090427/job/28151809671?pr=464)
[failing action](https://github.com/UCLH-Foundry/PIXL/actions/runs/10178090427/job/28151036968?pr=464)

**Comment by p-j-smith** [comment]
This came up again [here](https://github.com/UCLH-Foundry/PIXL/actions/runs/10511424867/job/29122356841?pr=489#step:9:2150) in #489, so I'll make a PR to fix it shortly

**Comment by p-j-smith** [comment]
The test failed again [here](https://github.com/SAFEHR-data/PIXL/actions/runs/10595380953/job/29361028150?pr=489#step:9:2012). It seems that the issue is that the zip file for procedure 4 is missing a DICOM - the should be [two DICOM files](https://github.com/SAFEHR-data/PIXL/blob/7b4de72c7dcd6f9171496062dfb6450f7f24d9cf/test/system_test.py#L38-L42) but for some reason there's only one:

<details>

<summary>failing test logs</summary>

> 2024-08-28 11:12:28.156 | INFO     | system_test:test_ftps_dicom_upload:146 - Checking tags in zip file /tmp/pytest-of-runner/pytest-0/ftps_server0/pixl_user/test-extract-uclh-omop-cdm/1.2.826.0.1.3680043.8.498.29449585099128098659945240939338361886.zip for **procedure 4**
>
> 2024-08-28 11:12:28.156 | INFO     | pytest_pixl.helpers:run_subprocess:40 - Running command ['unzip', PosixPath('/tmp/pytest-of-runner/pytest-0/ftps_server0/pixl_user/test-extract-uclh-omop-cdm/1.2.826.0.1.3680043.8.498.29449585099128098659945240939338361886.zip')]
>
> 2024-08-28 11:12:28.163 | INFO     | pytest_pixl.helpers:run_subprocess:56 - Success, returncode = 0
>
> 2024-08-28 11:12:28.164 | INFO     | pytest_pixl.helpers:run_subprocess:57 - stdout =
Archive:  /tmp/pytest-of-runner/pytest-0/ftps_server0/pixl_user/test-extract-uclh-omop-cdm/1.2.826.0.1.3680043.8.498.29449585099128098659945240939338361886.zip
>
> Created by Orthanc
>   inflating: 73e47d08d673b3e66af5494e38e5bc641cc8b18a3ca55d76de0c952783df9f25 > ANONYMIZED/ANONYMIZED STUDY/DX include123/DX000000.dcm  
>
> 2024-08-28 11:12:28.164 | INFO     | pytest_pixl.helpers:run_subprocess:58 - stderr =
> 
> 2024-08-28 11:12:28.164 | INFO     | system_test:_check_dcm_tags_from_zip:161 - In zip file, **1 DICOM files**: [PosixPath('/tmp/pytest-of-runner/pytest-0/unzip_dir0/73e47d08d673b3e66af5494e38e5bc641cc8b18a3ca55d76de0c952783df9f25 ANONYMIZED/ANONYMIZED STUDY/DX include123/DX000000.dcm')]

</details>

<details>

<summary>passing test logs</summary>

But running this locally when the test passes:

> 2024-08-28 13:05:43.948 | INFO     | system_test:test_ftps_dicom_upload:146 - Checking tags in zip file /private/var/folders/3x/026zvn0n35v9cg_b27xv40vm0000gn/T/pytest-of-paul/pytest-24/ftps_server0/pixl_user/test-extract-uclh-omop-cdm/1.2.826.0.1.3680043.8.498.58757953029345922266968443462295116445.zip for **procedure 4**
>
> 2024-08-28 13:05:50.915 | INFO     | pytest_pixl.helpers:run_subprocess:40 - Running command ['unzip', PosixPath('/private/var/folders/3x/026zvn0n35v9cg_b27xv40vm0000gn/T/pytest-of-paul/pytest-24/ftps_server0/pixl_user/test-extract-uclh-omop-cdm/1.2.826.0.1.3680043.8.498.58757953029345922266968443462295116445.zip')]
> 
> 2024-08-28 13:05:50.928 | INFO     | pytest_pixl.helpers:run_subprocess:56 - Success, returncode = 0
> 
> 2024-08-28 13:05:50.928 | INFO     | pytest_pixl.helpers:run_subprocess:57 - stdout =
Archive:  /private/var/folders/3x/026zvn0n35v9cg_b27xv40vm0000gn/T/pytest-of-paul/pytest-24/ftps_server0/pixl_user/test-extract-uclh-omop-cdm/1.2.826.0.1.3680043.8.498.58757953029345922266968443462295116445.zip
>
> Created by Orthanc
>   inflating: 73e47d08d673b3e66af5494e38e5bc641cc8b18a3ca55d76de0c952783df9f25 ANONYMIZED/ANONYMIZED STUDY/DX AP/DX000000.dcm  
>  inflating: 73e47d08d673b3e66af5494e38e5bc641cc8b18a3ca55d76de0c952783df9f25 ANONYMIZED/ANONYMIZED STUDY/DX include123/DX000000.dcm  
>
> 2024-08-28 13:05:50.929 | INFO     | pytest_pixl.helpers:run_subprocess:58 - stderr =
>
> 2024-08-28 13:06:03.187 | INFO     | system_test:_check_dcm_tags_from_zip:161 - In zip file, **2 DICOM files**: [PosixPath('/private/var/folders/3x/026zvn0n35v9cg_b27xv40vm0000gn/T/pytest-of-paul/pytest-24/unzip_dir1/73e47d08d673b3e66af5494e38e5bc641cc8b18a3ca55d76de0c952783df9f25 ANONYMIZED/ANONYMIZED STUDY/DX include123/DX000000.dcm'), PosixPath('/private/var/folders/3x/026zvn0n35v9cg_b27xv40vm0000gn/T/pytest-of-paul/pytest-24/unzip_dir1/73e47d08d673b3e66af5494e38e5bc641cc8b18a3ca55d76de0c952783df9f25 ANONYMIZED/ANONYMIZED STUDY/DX AP/DX000000.dcm')]

</details>

Any ideas why a DICOM series would be missing?
