### ISSUE TITLE
Few bits to improve readability and reproducibility 

### ISSUE THREAD

**Issue by mxochicale** [SAFEHR-data/PIXL#481]
* [x] bug report and feature request do not appear in the issue template selection https://github.com/UCLH-Foundry/PIXL/tree/main/.github/ISSUE_TEMPLATE
* [x] GitHub collapse markdown feature will improve readibility of main README, currently not consistent with different sections that can be added to READMEs in the setup path 
* [x] Adds further details on non-public links 
  *  To get access to the GAE, [see the documentation on Slab](https://uclh.slab.com/posts/gae-access-7hkddxap) main README
  * The [System design for linkage and export of imaging and EHR data](https://github.com/UCLH-Foundry/the-rolling-skeleton/blob/main/docs/design/system-design.md) document in the-rolling-skeleton repository provides an overview of the overall system architecture and the components that make up the system that PIXL is part of. https://github.com/UCLH-Foundry/PIXL/blob/main/docs/design/bigger_picture.md
* [x] Maybe add a debug section with common practices on debugging PIXL at https://github.com/UCLH-Foundry/PIXL/blob/main/docs/setup/developer.md Note. not too much bandwidth, so leave for future work
* [x] Rebasing branch should be changed from force push to fetch, merge main
* [x] fix spelling `addressed` in PR template

**Comment by milanmlft** [comment]
Regarding the bug report and feature request templates not appearing; it's because there are problems with the templates:

<img width="861" alt="image" src="https://github.com/user-attachments/assets/8c245426-bbc1-490c-80fe-ae4a54a1354f">

<img width="869" alt="image" src="https://github.com/user-attachments/assets/c3099800-0bed-4402-a77a-123cdb32bb4b">

**Comment by mxochicale** [comment]
Thanks Milan, I think this 0abe4bb fixes the issues with templates issues :) I will request PRs soon. This pre-commit hook might be useful  https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-issue-forms.json
