### ISSUE TITLE
Recover from partial transfers of DICOM from source

### ISSUE THREAD

**Issue by stefpiatek** [SAFEHR-data/PIXL#486]
### Definition of Done / Acceptance Criteria

Currently the pipeline deletes a study if it becomes stable but doesn't have the custom DICOM tag for pixl project set. We should allow for a graceful recovery from a DICOM that failed transfer midway, only downloading the data that hasn't previously been transferred.

#### User story

As a hospital clinical imaging team administrator, I want PIXL to only query for DICOM instances that it doesn't already have, rather pulling an entire study again if it has failed mid-transfer

### Testing

set up unit test with partial data in sent to orthanc raw, full data in VNA and ensure that its reprocessed. Perhaps putting a spy on the method to query for a single instance and ensure that its only the untransferred instances

### Documentation

*No response*

### Dependencies

*No response*

### Details and Comments

Did some investigation with @HChughtai and it looks like its reasonably nice to find the instance UIDs. Suggested flow would be something like this

* Check if study exists in orthanc raw
  * if it doesn't exist, query at the study level as we currently do
  * if exists,
    * if the number of instance UIDs matches between VNA and orthanc raw, if the pixl project tag matches then send it to orthanc anon and return early
    * if they don't have the same number then build a set of all of the instance UIDs in the VNA. Compare this with a set of instance UIDs in orthanc raw.
      * download any missing instances,
  * update the pixl project tag value as we currently do
  * send to orthanc anon directly (and remove our sending on DICOM stable in the `pixl` plugin in orthanc raw

I *think* pyorthanc can do async requests so could be a good time to move to that instead of rolling our own. Here's an example that we did using curl using the values

```
curl --request POST \
  --noproxy "*" \
  -u "pixl:${PIXL_PASSWORD}" \
  --url http://localhost:9006/modalities/UCVNAQR/query \
  --data '{
            "Level" : "Study",
            "Query" : {
              "PatientID" : "${PATIENT_ID}",
              "AccessionNumber": "${ACCESSION_NUMBER}"
            }
          }'
```

> {
> "ID" : "${STUDY_QUERY_ID}",
> "Path" : "/queries/${STUDY_QUERY_ID}"
> }(

studies found

```
curl --noproxy "*" \
  -u "pixl:${PIXL_PASSWORD}" \
  --url http://localhost:9006/queries/${STUDY_QUERY_ID}/answers
```

> \[
> "0",
> "1"
> \](

get the instances for a study, would need to iterate over studies if there are multiple (which does happen by mrn and accession number)

```
curl --request POST \
 --noproxy "*" \
  -u "pixl:${PIXL_PASSWORD}" \
  --url http://localhost:9006/queries/${STUDY_QUERY_ID}/answers/0/query-instances \
  --data '{
            "Query" : {
            },
            "Timeout": 0
          }'
```

> {
> "ID" : "${INSTANCES_QUERY_ID}",
> "Path" : "/queries/${INSTANCES_QUERY_ID}"
> }(

total number of instances, could check if the number of instances is the same between the two servers. if not then compare each SOPInstanceUID

```
curl --noproxy "*" \
  -u "pixl:${PIXL_PASSWORD}" \
  --url http://localhost:9006/queries/${INSTANCES_QUERY_ID}/answers
```

> \[
> "0",
> ...
> "652"
> \]

Get the instance uid (SOPInstanceUID)

```
curl --noproxy "*" \
  -u "pixl:${PIXL_PASSWORD}" \
  --url http://localhost:9006/queries/${INSTANCES_QUERY_ID}/answers/0/content
```

> { "0002,0003" : { "Name" : "MediaStorageSOPInstanceUID", "Type" : "String", "Value" : "REDACTED" }, "0008,0005" : { "Name" : "SpecificCharacterSet", "Type" : "String", "Value" : "ISO_IR 100" }, "0008,0018" : { "Name" : "SOPInstanceUID", "Type" : "String", "Value" : "REDACTED" }, "0008,0050" : { "Name" : "AccessionNumber", "Type" : "String", "Value" : "REDACTED" }, "0008,0052" : { "Name" : "QueryRetrieveLevel", "Type" : "String", "Value" : "IMAGE" }, "0008,0054" : { "Name" : "RetrieveAETitle", "Type" : "String", "Value" : "REDACTED" }, "0010,0020" : { "Name" : "PatientID", "Type" : "String", "Value" : "REDACTED" }, "0020,000d" : { "Name" : "StudyInstanceUID", "Type" : "String", "Value" : "REDACTED" }, "0020,000e" : { "Name" : "SeriesInstanceUID", "Type" : "String", "Value" : "REDACTED" }

**Comment by p-j-smith** [comment]
I might be doing something wrong but I think the `StudyInstanceUID`, and `SeriesInstanceUID`, and `SOPInstanceUID` values are modified by Orthanc Raw when retrieving data from the archives, which means we can't compare `SOPInstanceUID`s to check for existing instances. I'll open a PR with a test to check the `StudyInstanceUID` in Orthanc Raw is the same as in the VNA (assuming this is the expected behaviour?)
