### ISSUE TITLE
Give Stef access to UCLHSDE azure tenancy

### ISSUE THREAD

**Issue by stefpiatek** [SAFEHR-data/PIXL#490]
No rush at this stage but should sort have access to the tenancy so make sure PIXL infrastructure can run without issues

Should be able to:

* update secrets for hasher api: `kv-pixld-c-flowehr-prod`
* update client secret for access that we store in HASHER_API_AZ_CLIENT_PASSWORD
* create, update and delete secrets for `kv-pixl-prod`
* update client secret for access that we store in EXPORT_AZ_CLIENT_PASSWORD

**Comment by dram1964** [comment]
Hi @stefpiatek - I've sent an invite to your nhs.net email to sign-up on the SDE tenant. This account is a member of the pixl-key-vault group and should therefore give you access to the two key vaults in SDE used by PIXL. Let me know if that works for you or not.
