### ISSUE TITLE
Create default anonymisation for spectroscopy data

### ISSUE THREAD

**Issue by mxochicale** [SAFEHR-data/PIXL#511]
Actions
* [x] Discuss with James Moggridge and Matthew Grech Sollars on what they have done for de-identification,
* [x] Add the spectroscopy specific ones to a new tag-operations config file,
* [ ] Run through and share de-id files with them, to see if they are still usable.

Pre-requisites:
* [x] JM to share data to PIXL team

Notes:
* Data formats are in *.dcm (for Vida/Sola but not in Prisma/Skyra), *.rda (currently used in Prisma), and *.IMA (for Prisma/Skyra but not supported in Vida/Sola), 
* No scope for rda or IMA data at this stage
* Logs from DICOM validation in pixl_test-orthanc-anon-1:
  * ```pixl_dev-orthanc-anon-1  | KeyError: 'Tag (0018,9240) (RF Echo Train Length) is empty in  Multi-frame Functional Groups > (5200,9229) > (0018,9112)'```
     * RF Echo Train Length Attribute Tag	(0018,9240): https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009230/00189112/00189240 
  * ```pixl_test-orthanc-anon-1  |     |      |        -> {'Tag (0018,9112) (MR Timing and Related Parameters Sequence) is missing in  Multi-frame Functional Groups > (5200,9230)': ['...```
     * MR Timing and Related Parameters Sequence Attribute (0018,9112) https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009230/00189112
  * https://github.com/SAFEHR-data/the-rolling-skeleton/issues/377
* ...

**Comment by p-j-smith** [comment]
@p-j-smith and @mxochicale met with James Moggridge for further info on adding support for spectroscopy data:

- Will the scanners also be producing `.rda` or `.ima` files and should we be planning to support these?
	- `.ima` files are legacy files produced by Siemans scanners. The scanners scanners in Grays Inn Road will produce `.dcm` files instead, so `.ima` files can be ignored. The plan is to export the DICOM from the scanners and upload to PACS, then PIXL can pull from there.
	- `.rda` files may also be produced by the scanners and it would be good to support these. Ideally the `.rda` files will be handled in the same way as raw data (uploading to shared storage on the network and have PIXL pull it from there). We also need to think about where `.rda` files will be sent (assuming XNAT doesn't support them), and how to link images send to XNAT with ``.rda files stored elsewhere

- the sample data James has shared is phantom data. However, it may contain operator data that will need anonymising before using in PIXL unit tests. Alternatively, there is anonymised sample spectroscopy data available from a researcher (Chris Roden?). The researcher also has sample data for various scanners (Siemans, Phillips, ...) which may be useful in the future
    
- once we have passed the data through the anonymisation pipeline, James will check that he can still run his analysis on it
    
- all tags specific to spectroscopy can probably be kept, although we need to check the private tags added by Siemans in case these contain PII
