### ISSUE TITLE
Allow for concurrent orthanc-anon processing 

### ISSUE THREAD

**Issue by stefpiatek** [SAFEHR-data/PIXL#524]
### What happened?

- The api call for `orthanc-anon` to import from `raw` doesn't seem to block, so there are multiple requests to CMOVE all concurrently
- There is only ever one CMOVE at a time, so it appears like the CMOVE is a blocking operation
- This then can cause `orhtanc-anon` to crash

### What did you expect? (optional)

- Hopefully downloading the zip archive directly from `orthanc-raw` will not be blocking so that may solve this, if not then I expect the plugin listed in #507 will resolve this
- We should also limit the number of concurrent studies de-identified at once. Republishing the same message to a new queue that orthanc-anon plugin reads could be a good option, then we don't use the API at all but instead read in from that and use the same max in flight?

**Comment by p-j-smith** [comment]
#523 moved the processing in `orthanc-anon` into background threads using a `ThreadPoolExecutor` with the number of workers set to `PIXL_MAX_MESSAGES_IN_FLIGHT`. So hopefully we're not blocking the main thread anymore, and the `ThreadPoolExecutor` will handle the queuing to ensure only 5 studies are de-identified at any time.

But let's leave the issue open in case we're still having these problems.
